#!/usr/bin/env bash
# Assemble the LaTeX source archive ACS asks for as the "Manuscript File".
#
# This existed as a manual copy-and-zip for three rebuilds, which is exactly long
# enough for it to drift: the staging README claimed 17 pages while the compiled
# article had grown to 18. The page count is now read from the pdf instead of
# being typed, so it cannot disagree with what is shipped.
#
# Only the files main_jctc.tex actually needs are included. The full artifact
# (code, records, manifests) is NOT here -- that is the public repository cited in
# the availability statement, and duplicating it into a submission archive would
# imply the reviewer must audit it to read the paper.
set -euo pipefail

cd "$(dirname "$0")/../paper"
OUT="jctc_manuscript_source.zip"
STAGE="jctc_manuscript_source"

[[ -f main_jctc.pdf ]] || { echo "main_jctc.pdf missing -- run build_jctc.sh first" >&2; exit 1; }

PAGES=$(pdfinfo main_jctc.pdf | awk '/^Pages/{print $2}')
[[ -n "$PAGES" ]] || { echo "could not read page count" >&2; exit 1; }

rm -rf "$STAGE" "$OUT"
mkdir -p "$STAGE/figures" "$STAGE/tables"

cp main_jctc.tex body.tex macros.tex artifact.tex references.bib "$STAGE/"
cp main_jctc.pdf "$STAGE/manuscript_compiled.pdf"
cp figures/fig1_factor_a.pdf figures/fig2_gate_forest.pdf figures/fig3_extensivity.pdf \
   figures/fig4_speedup.pdf figures/fig5_beta_law.pdf "$STAGE/figures/"
cp tables/table_pairs.tex tables/table_mptraj.tex "$STAGE/tables/"

cat > "$STAGE/README.txt" <<TXT
LaTeX source for submission to J. Chem. Theory Comput.

  main_jctc.tex   root file; achemso, journal=jctcce, manuscript=article
  body.tex        abstract and all sections (shared verbatim with the preprint
                  and ICLR builds, so a correction reaches all of them at once)
  macros.tex      GENERATED, do not edit by hand. Every numeric value in the
                  manuscript is derived from a committed experimental record by
                  tools/paper_numbers.py and re-checked by tools/audit.py; none
                  is transcribed.
  artifact.tex    the artifact locator, kept out of the generated macros.tex so
                  a build cannot overwrite it
  references.bib  12 entries, each verified against the publisher record by DOI
                  content negotiation
  figures/        five vector PDFs, generated by tools/make_figures.py
  tables/         two generated tables

  manuscript_compiled.pdf   the compiled article, for reference

Build:  pdflatex main_jctc -> bibtex main_jctc -> pdflatex x2
Verified with TeX Live 2025: 0 errors, 0 overfull boxes, 0 undefined references
or citations, ${PAGES} pages.
TXT

( cd "$STAGE" && zip -q -r "../$OUT" . -x '.*' )
echo "== wrote paper/$OUT ($(stat -c%s "$OUT") bytes, ${PAGES}-page article)"
unzip -l "$OUT" | tail -3
